name: CI - CalculadoraAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  q4-snyk:
      name: Q4 - Security (Snyk Code)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "8.0.x"
  
        - name: Setup Snyk
          uses: snyk/actions/setup@master
  
        - name: Restore solution
          run: dotnet restore ./Calculadora.sln
  
        - name: Q4 - Dependency vulnerability scan
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk test --file=./Calculadora.sln --severity-threshold=high

  build-and-test:
    runs-on: ubuntu-latest
    needs: q4-snyk
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar la solución
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar tests (unitarios + integración)
        run: dotnet test --no-build --configuration Release --verbosity normal